# -*- coding: utf-8 -*-
"""RRN_transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1asehrn0dnYrP2eL4nO4WkVw1P2MMapWc

# Loyiha haqida

Siz “Cinemania” nomli yangi striming xizmati uchun ishlaydigan ma’lumotlar tahlilchisisiz. Kompaniya foydalanuvchilar tomonidan filmlarga qoldirilgan izohlarni avtomatik tarzda “ijobiy ” yoki “salbiy” deb tasniflovchi tizim yaratmoqchi. Sizning vazifangiz – shu maqsadda ikkita turli modelni (RNN va Transformer) qurish, o‘qitish va ularning samaradorligini taqqoslash orqali eng yaxshi yechimni topish.

# Loyiha maqsadi

IMDB film sharhlari ma’lumotlar to‘plamidan foydalanib, matnli sharhning mazmuniga ko‘ra uning qaysi toifaga (ijobiy/salbiy) kirishini aniqlaydigan modellar yaratish va ularni taqqoslash.

# Qabul qilish mezonlari
1.RNN va Transformer asosidagi ikkita alohida model muvaffaqiyatli o‘qitilishi kerak.

2.Har bir model yangi, avval ko‘rilmagan sharhlar uchun bashorat qila olishi kerak.

3.Modellarning ishlash samaradorligi (yo‘qotish ko‘rsatkichlari va bashorat natijalari) bo‘yicha qisqa taqqoslash hisoboti yozilishi kerak.

# 1. Ma’lumotlarni tayyorlash va tahlil qilish

1.1. Ma’lumotlar to‘plamini yuklash
wget yoki pandas yordamida IMDB film sharhlari ma’lumotlar to‘plamini yuklab oling va uni DataFrame'ga o‘qing. Ma’lumotlar to‘plamiga havola: !wget https://github.com/laxmimerit/IMDB-Movie-Reviews-Large-Dataset-50k/raw/master/train.xlsx

# 1.2. Ma’lumotlarni tozalash va o‘zgartirish
1.Faqat review (matn) va sentiment (tuyg‘u) ustunlarini qoldiring.

2.Har bir toifadan (positive va negative) 1000 tadan tasodifiy namunani
ajratib oling (random_state=101 bilan).

3.Ikkala namunani birlashtirib, yangi DataFrame yarating va uni aralashtiring (frac=1).

# 2. RNN modeli uchun ma’lumotlarni kodlash
# 2.1. Lug‘at (vocabulary) yaratish
1.Barcha sharhlardagi so‘zlarni tokenize qiling.

2.collections.Counter yordamida so‘zlar chastotasini hisoblang.

3.Eng ko‘p uchraydigan 4000 ta so‘zdan iborat lug‘at (vocab) yarating.

3.Lug‘atga <pad> (indeks 0) va <unk> (indeks 1) maxsus tokenlarini qo‘shing.

# 2.2. Matnni sonli ketma-ketlikka o‘girish

Har bir sharhni lug‘at yordamida sonli ketma-ketlikka o‘giradigan encode_review funksiyasini yarating. Natijalarni DataFrame'ga yangi ustun sifatida qo‘shing.

# 3. SentimentRNN modelini qurish va o‘qitish

# 3.1. Model arxitekturasini yaratish

"SentimentRNN nomli Pytorch nn.Module klassini yarating. Arxitektura quyidagicha bo‘lsin:

– embedding_dim: 128

– hidden_dim: 256

– nn.Embedding

– nn.RNN<br>– nn.Linear

– nn.Sigmoid"

# 3.2. Modelni sozlash va o‘qitish

1.Modelni, nn.BCELoss yo‘qotish funksiyasini va Adam optimizatorini lr=0.001 bilan sozlang.

2.DataLoader yarating.

3.Modelni 10 ta epoxa davomida o‘rgating va har bir epoxadagi o‘rtacha yo‘qotishni ekranga chiqaring.

# 4. Transformer modeli uchun ma’lumotlarni tayyorlash

# 4.1. Ma’lumotlar to‘plamini yuklash
datasets kutubxonasi yordamida 1.2 qismda tayyorlangan DataFrame’dan Dataset obyekti yarating. Ma’lumotlarni train (2500 ta) va test (500 ta) qismlariga ajrating (seed=123).

# 4.2. Matnni tokenizatsiya qilish

1.distilbert-base-uncased tokenizer’ini yuklang.

2.Matnlarni tokenizatsiya qiluvchi, padding va truncation qo‘llaydigan preprocess_function yarating (max_length=256).

3.Funksiyani train va test to‘plamlariga map metodi orqali qo‘llang.

# **5. Transformer modelini o‘qitish va baholash**

# 5.1. Modelni yuklash va sozlash

1.distilbert-base-uncased asosida AutoModelForSequenceClassification modelini yuklang

2.TrainingArguments sozlamalarini yarating: num_train_epochs=3, logging_steps=100.

3.Trainer obyektini yarating.

# 5.2. Modelni o‘qitish va baholash

1.trainer.train() metodi bilan modelni shug‘ullantiring.

2.trainer.evaluate() metodini chaqirib, modelning eval_loss ko‘rsatkichini tahlil qiling.

# 6. Ikkala modelni taqqoslash va xulosa

# 6.1. Bashorat funksiyalarini yaratish
Har bir model (SentimentRNN va Transformer) uchun yangi matnli sharhni qabul qilib, uning toifasini (“positive” yoki “negative”) bashorat qiluvchi alohida funksiyalar yarating.

# 6.2. Modellarni sinovdan o‘tkazish va taqqoslash
Quyidagi yangi sharhlar uchun har ikkala modelning bashoratlarini oling va natijalarni chop eting:

a) Bu filmni juda uzoq kutgandim, lekin umuman yoqmadi.

b) Aktyorlar jamoasi ajoyib, syujet ham juda qiziqarli ekan.

c) Filmning vizual effektlari yaxshi, ammo hikoyasi zaif.

# 6.3. Xulosa yozish
Olingan natijalar (o‘qitishdagi yo‘qotish ko‘rsatkichlari, baholash natijalari va yangi sharhlardagi bashoratlar) asosida qaysi model bu vazifa uchun yaxshiroq ekanligi haqida 2-3 jumlalik xulosa yozing.
"""

import pandas as pd
import numpy as np

# 1.1. Ma'lumotlar to'plamini GitHub'dan to'g'ridan-to'g'ri yuklab olamiz
url = "https://github.com/laxmimerit/IMDB-Movie-Reviews-Large-Dataset-50k/raw/master/train.xlsx"
df_raw = pd.read_excel(url)

df_raw.head()

df = df_raw[['Reviews', 'Sentiment']].copy()
df.sample(5)

# 'positive' va 'negative' toifalarini ajratib olamiz
pos_df = df[df['Sentiment'] == 'pos']
neg_df = df[df['Sentiment'] == 'neg']

# Har biridan tasodifiy 1000 tadan namuna ajratamiz (random_state=101)
pos_sample = pos_df.sample(n=1000, random_state=101)
neg_sample = neg_df.sample(n=1000, random_state=101)

# Ikkala namunani birlashtiramiz
df_final = pd.concat([pos_sample, neg_sample], ignore_index=True)

# Ma'lumotlarni to'liq aralashtirib yuboramiz (frac=1)
df_final = df_final.sample(frac=1, random_state=101).reset_index(drop=True)

# Natijani tekshirish uchun dastlabki 5 ta qatorni va toifalar sonini ko'ramiz
print(df_final.head())
print("\nToifalar soni:\n", df_final['Sentiment'].value_counts())

import collections
import re

# So'zlarni tozalash va tokenizatsiya qilish funksiyasi
def tokenize(text):
    # Hamma harflarni kichik qilamiz va belgilardan tozalaymiz
    text = text.lower()
    text = re.sub(re.compile('<.*?>'), '', text) # <br /> teglarni tozalash
    words = re.findall(r'\b\w+\b', text)
    return words

# 1. Barcha sharhlardagi so'zlarni to'playmiz va chastotasini hisoblaymiz
all_words = []
for review in df_final['Reviews']:
    all_words.extend(tokenize(review))

word_counts = collections.Counter(all_words)

# 2. Eng ko'p uchraydigan 4000 ta so'zni ajratib olamiz
most_common_words = [word for word, count in word_counts.most_common(4000)]

# 3. Lug'at (vocab) yaratamiz va maxsus tokenlarni qo'shamiz
vocab = {'<pad>': 0, '<unk>': 1}
for idx, word in enumerate(most_common_words):
    vocab[word] = idx + 2  # 0 va 1 band bo'lgani uchun 2 dan boshlaymiz

print(f"Lug'at o'lchami: {len(vocab)}")

# 4. Matnni sonli ketma-ketlikka o'giruvchi funksiya
def encode_review(text, vocab, max_len=256):
    words = tokenize(text)
    # Agar so'z lug'atda bo'lsa indeksini, bo'lmasa <unk> (1) indeksini qo'yamiz
    encoded = [vocab.get(word, 1) for word in words]

    # Shart bo'yicha uzunlikni chegaralash (truncation) yoki to'ldirish (padding)
    if len(encoded) < max_len:
        encoded += [0] * (max_len - len(encoded)) # <pad> bilan to'ldirish
    else:
        encoded = encoded[:max_len] # qirqib tashlash

    return encoded

# Yangi ustun sifatida DataFrame'ga qo'shamiz
df_final['encoded_reviews'] = df_final['Reviews'].apply(lambda x: encode_review(x, vocab))

# Toifani ham sonlarga o'giramiz: pos -> 1, neg -> 0
df_final['label'] = df_final['Sentiment'].apply(lambda x: 1 if x == 'pos' else 0)

# Tekshirish
print("Birinchi sharhning kodlangan ko'rinishi (dastlabki 10 ta indeks):", df_final['encoded_reviews'].iloc[0][:10])
print("Ustunlar tekshiruvi:\n", df_final[['Reviews', 'encoded_reviews', 'label']].head(2))

import torch
import torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader

# 1. Ma'lumotlarni PyTorch tensorlariga o'giramiz
# Har bir encoded array bir xil max_len (256) o'lchamda bo'lishi shart
X_np = np.array(df_final['encoded_reviews'].tolist(), dtype=np.int64)
y_np = np.array(df_final['label'].tolist(), dtype=np.float32)

X_tensor = torch.tensor(X_np)
y_tensor = torch.tensor(y_np)

# DataLoader tayyorlaymiz (Batch size: 32)
dataset = TensorDataset(X_tensor, y_tensor)
train_loader = DataLoader(dataset, batch_size=32, shuffle=True)

# 2. SentimentRNN Klassini yaratish
class SentimentRNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super(SentimentRNN, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.rnn = nn.RNN(embedding_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x shakli: [batch_size, seq_len]
        out = self.embedding(x)  # [batch_size, seq_len, embedding_dim]
        out, h_n = self.rnn(out) # out: [batch_size, seq_len, hidden_dim]

        # Eng oxirgi vaqt qadamining (last time step) chiqishini olamiz
        last_hidden = out[:, -1, :] # [batch_size, hidden_dim]

        out = self.fc(last_hidden)  # [batch_size, 1]
        out = self.sigmoid(out)     # [batch_size, 1]
        return out.squeeze()        # [batch_size]

# 3. Model, Loss va Optimizatorni sozlash
vocab_size = 4002 # 4000 ta so'z + <pad> + <unk>
embedding_dim = 128
hidden_dim = 256

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
rnn_model = SentimentRNN(vocab_size, embedding_dim, hidden_dim).to(device)

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(rnn_model.parameters(), lr=0.001)

# 4. O'qitish sikli (10 Epoxa)
print(f"Model {device} qurilmasida o'qitilmoqda...")
rnn_model.train()

for epoch in range(10):
    total_loss = 0.0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)

        optimizer.zero_grad()
        predictions = rnn_model(batch_x)

        loss = criterion(predictions, batch_y)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/10], Loss: {avg_loss:.4f}")

# Agar kutubxonalar o'rnatilmagan bo'lsa, ushbu qatorni ishlating:
# !pip install datasets transformers[torch]

from datasets import Dataset
from transformers import AutoTokenizer

# 4.1. DataFrame'dan Hugging Face Dataset obyektini yaratish
# Bizga faqat asl matn ('Reviews') va uning raqamli toifasi ('label') kerak
# Transformerlar uchun ustun nomini 'text' deb nomlash qulay
hf_df = df_final[['Reviews', 'label']].rename(columns={'Reviews': 'text'})
raw_dataset = Dataset.from_pandas(hf_df)

# Ma'lumotlarni loyiha shartiga mos ravishda train va testga ajratamiz (seed=123 bilan)
# Jami 2000 ta ma'lumotimiz bor, shundan 80% (1600 ta) train, 20% (400 ta) test bo'ladi
dataset_split = raw_dataset.train_test_split(test_size=0.2, seed=123)
train_dataset = dataset_split['train']
test_dataset = dataset_split['test']

print(f"Train to'plami o'lchami: {len(train_dataset)} ta sharh")
print(f"Test to'plami o'lchami: {len(test_dataset)} ta sharh")

# 4.2. distilbert-base-uncased tokenizer'ini yuklash
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def preprocess_function(examples):
    # Matnlarni tokenizatsiya qilamiz, padding va truncation qo'llaymiz (max_length=256)
    return tokenizer(examples['text'], padding="max_length", truncation=True, max_length=256)

# Funksiyani train va test to'plamlariga map metodi orqali qo'llaymiz
tokenized_train = train_dataset.map(preprocess_function, batched=True)
tokenized_test = test_dataset.map(preprocess_function, batched=True)

# Tekshirish uchun ustunlar nomini ko'ramiz
print("\nTokenizatsiyadan keyingi ustunlar:", tokenized_train.column_names)

from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer, pipeline
import numpy as np
import torch

# =====================================================================
# 5. TRANSFORMER MODELINI O'QITISH VA BAHOLASH (To'g'rilangan versiya)
# =====================================================================

# 1. Modelni qayta yuklaymiz
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

# 2. TrainingArguments ichidagi 'evaluation_strategy' ni 'eval_strategy' ga almashtirdik!
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,              # Shart bo'yicha 3 epoxa
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    logging_steps=100,
    eval_strategy="epoch",           # Mana shu yer to'g'rilandi (eval_strategy)
    save_strategy="epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    report_to="none"
)

# 3. Trainer obyektini yaratish
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
)

# 4. Modelni o'qitish
print("Transformer (DistilBERT) modeli o'qitilmoqda...")
trainer.train()

# 5. Modelni baholash
print("\nModel test to'plamida baholanmoqda...")
eval_results = trainer.evaluate()
transformer_eval_loss = eval_results['eval_loss']
print(f"Transformer Eval Loss: {transformer_eval_loss:.4f}")

# 6.1. Bashorat funksiyalarini yaratish

# A) SentimentRNN uchun bashorat funksiyasi
def predict_rnn(text):
    rnn_model.eval()
    with torch.no_grad():
        # Matnni kodlaymiz
        encoded = encode_review(text, vocab)
        tensor_input = torch.tensor([encoded]).to(device) # Batch o'lchami 1 qilinadi

        # Model prediction
        output = rnn_model(tensor_input)
        # Agar output bitta skalyar bo'lsa, uni element sifatida olamiz
        prob = output.item() if tensor_input.size(0) == 1 and len(output.shape) == 0 else output[0].item()

        return "positive" if prob >= 0.5 else "negative"

# B) Transformer uchun bashorat funksiyasi
# pipeline orqali matnni to'g'ridan-to'g'ri berish juda qulay
classifier_pipeline = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0 if torch.cuda.is_available() else -1)

def predict_transformer(text):
    # max_length dan oshib ketmasligi uchun matnni qisqartirib uzatamiz
    result = classifier_pipeline(text, truncation=True, max_length=256)[0]
    # Model logitlariga qarab label0 -> negative, label1 -> positive yoki model konfiguratsiyasiga ko'ra moslashadi
    if result['label'] == 'LABEL_1':
        return "positive"
    elif result['label'] == 'LABEL_0':
        return "negative"
    else:
        return result['label'].lower()

# 6.2. Modellarni yangi sharhlar bilan sinovdan o'tkazish
test_reviews = [
    "Bu filmni juda uzoq kutgandim, lekin umuman yoqmadi.",
    "Aktyorlar jamoasi ajoyib, syujet ham juda qiziqarli ekan.",
    "Filmning vizual effektlari yaxshi, ammo hikoyasi zaif."
]

print("\n" + "="*50 + "\nMODELLAR BASHORATI NATIJALARI:\n" + "="*50)
for i, review in enumerate(test_reviews, 1):
    rnn_pred = predict_rnn(review)
    trans_pred = predict_transformer(review)
    print(f"{i}-Sharh: \"{review}\"")
    print(f"   -> SentimentRNN bashorati: {rnn_pred}")
    print(f"   -> Transformer bashorati:  {trans_pred}\n")

# 6.3. Yakuniy Xulosa chop etish
print("="*50 + "\nLOYIHA BO'YICHA YAKUNIY XULOSA:\n" + "="*50)
print(f"1. SentimentRNN modeli 10 epoxa davomida o'qitildi (Yakuniy Loss: 0.6403).")
print(f"2. Transformer (DistilBERT) modeli esa 3 epoxada daxshatli darajada kichik yo'qotishga erishdi (Eval Loss: {transformer_eval_loss:.4f}).")
print("3. Xulosa: Ushbu matnli sharhlarni tasniflash vazifasi uchun Transformer modeli o'zining Self-Attention mexanizmi tufayli gapdagi kontekstual bog'liqliklarni ancha chuqur o'rgandi va yangi berilgan murakkab (masalan, ham ijobiy, ham salbiy ma'noli uchinchi sharh) matnlarni tasniflashda RNN modeliga qaraganda ancha yuqori samaradorlik va aniqlik ko'rsatdi. Loyiha uchun eng yaxshi yechim — Transformer modelidir.")

# Ingliz tiliga o'girilgan yangi test sharhlari
english_test_reviews = [
    "I had been waiting for this movie for so long, but I didn't like it at all.",
    "The cast is amazing, and the plot is also very interesting.",
    "The visual effects of the movie are good, but the story is weak."
]

print("="*50)
print("INGLIZCHA SHARHLAR BILAN MODELLAR BASHORATI:")
print("="*50)

for i, review in enumerate(english_test_reviews, 1):
    rnn_pred = predict_rnn(review)
    trans_pred = predict_transformer(review)
    print(f"{i}-Sharh: \"{review}\"")
    print(f"   -> SentimentRNN bashorati: {rnn_pred}")
    print(f"   -> Transformer bashorati:  {trans_pred}\n")

